import turtle

window = turtle.Screen()
window.setup(1000,600)
window.bgcolor("pink")
window.title("Homework3")

ori = turtle.Turtle()
ori.shape("turtle")
ori.pencolor("black")
ori.pensize(3)
ori.speed(0)

ori.circle(30)
ori.right(90)
ori.forward(100)
print(ori.pos())
ori.right(25)
ori.forward(50)
ori.penup()
ori.goto(-0,-100)
ori.pendown()
ori.left(50)
ori.forward(50)
ori.penup()
ori.goto(-35,-50)
ori.pendown()
ori.left(65)
ori.forward(70)
turtle.done()