import turtle

window = turtle.Screen()
window.setup(1000,600)
window.bgcolor("orange")
window.title("Homework3")

ori = turtle.Turtle()
ori.shape("turtle")
ori.pencolor("black")
ori.pensize(3)
ori.speed(0)

ori.circle(30)
ori.right(90)
ori.forward(100)
ori.right(25)
ori.forward(50)
ori.penup()
ori.goto(-0,-100)
ori.pendown()
ori.left(50)
ori.forward(50)
ori.penup()
ori.goto(-35,-50)
ori.pendown()
ori.left(65)
ori.forward(70)

ori.penup()
ori.goto(-50,50)
ori.pendown()
ori.fillcolor("brown")
ori.begin_fill()
ori.forward(100)
ori.left(135)
ori.forward(10)
ori.left(45)
ori.forward(88)
ori.left(45)
ori.forward(10)
ori.end_fill()

ori.penup()
ori.goto(0,0)

turtle.done()