import turtle

window = turtle.Screen()
window.setup(1000,600)
window.bgcolor("orange")
window.title("Homework3")

ori = turtle.Turtle()
ori.shape("turtle")
ori.pencolor("black")
ori.pensize(3)
ori.speed(0)

ori.hideturtle()

ori.circle(30)
ori.right(90)
ori.forward(100)
ori.right(25)
ori.pencolor("blue")
ori.forward(50)
ori.penup()
ori.goto(-0,-100)
ori.pendown()
ori.left(50)
ori.forward(50)
ori.penup()
ori.pencolor("black")
ori.goto(0,-50)
ori.pendown()
ori.left(65)
ori.forward(35)

ori.penup()
ori.goto(-50,50)
ori.pendown()
ori.fillcolor("brown")
ori.begin_fill()
ori.forward(100)
ori.left(135)
ori.forward(10)
ori.left(45)
ori.forward(88)
ori.left(45)
ori.forward(10)
ori.end_fill()
ori.penup()

ori.goto(-30,58)
ori.pendown()
ori.fillcolor("brown")
ori.begin_fill()
ori.right(145)
ori.forward(20)
ori.right(80)
ori.forward(50)
ori.right(80)
ori.forward(20)
ori.end_fill()

ori.penup()
ori.goto(7,40)
ori.pendown()
ori.left(55)
ori.forward(10)

ori.penup()
ori.goto(7,25)
ori.pendown()
ori.pencolor("blue")
ori.fillcolor("blue")
ori.begin_fill()
ori.circle(3)
ori.end_fill()

ori.penup()
ori.pencolor("gray")
ori.fillcolor("gray")
ori.begin_fill()
ori.left(25)
ori.goto(30,-35)
ori.pendown()
ori.forward(30)
ori.right(90)
ori.forward(5)
ori.right(90)
ori.forward(25)
ori.left(90)
ori.forward(15)
ori.right(90)
ori.forward(5)
ori.right(90)
ori.forward(20)
ori.end_fill()



turtle.done()